src/web/NSE.WebApp.MVC/Models/EnderecoViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace NSE.WebApp.MVC.Models
{
    public class EnderecoViewModel
    {
        [Required]
        public string Logradouro { get; set; }
        [Required]
        [DisplayName("Número")]
        public string Numero { get; set; }
        public string Complemento { get; set; }
        [Required]
        public string Bairro { get; set; }
        [Required]
        [DisplayName("CEP")]
        public string Cep { get; set; }
        [Required]
        public string Cidade { get; set; }
        [Required]
        public string Estado { get; set; }

        public override string ToString()
        {
            return $"{Logradouro}, {Numero} {Complemento} - {Bairro} - {Cidade} - {Estado}";
        }
    }
}

src/web/NSE.WebApp.MVC/Models/PedidoViewModel.cs
using System;
using System.Collections.Generic;

namespace NSE.WebApp.MVC.Models
{
    public class PedidoViewModel
    {
        #region Pedido

        public int Codigo { get; set; }

        // Autorizado = 1,
        // Pago = 2,
        // Recusado = 3,
        // Entregue = 4,
        // Cancelado = 5
        public int Status { get; set; }
        public DateTime Data { get; set; }
        public decimal ValorTotal { get; set; }

        public decimal Desconto { get; set; }
        public bool VoucherUtilizado { get; set; }

        public List<ItemPedidoViewModel> PedidoItems { get; set; } = new List<ItemPedidoViewModel>();

        #endregion

        #region Item Pedido

        public class ItemPedidoViewModel
        {
            public Guid ProdutoId { get; set; }
            public string Nome { get; set; }
            public int Quantidade { get; set; }
            public decimal Valor { get; set; }
            public string Imagem { get; set; }
        }

        #endregion

        #region Endereco

        public EnderecoViewModel Endereco { get; set; }

        #endregion
    }
}

src/web/NSE.WebApp.MVC/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NSE.WebApp.MVC.Models;
using NSE.WebApp.MVC.Service;
using System.Linq;
using System.Threading.Tasks;

namespace NSE.WebApp.MVC.Controllers
{
    [Authorize]
    public class ClienteController : MainController
    {
        private readonly IClienteService _clienteService;

        public ClienteController(IClienteService clienteService)
        {
            _clienteService = clienteService;
        }

        [HttpPost]
        public async Task<IActionResult> NovoEndereco(EnderecoViewModel endereco)
        {
            var response = await _clienteService.AdicionarEndereco(endereco);

            if (ResponsePossuiErros(response)) TempData["Erros"] =
                ModelState.Values.SelectMany(v => v.Errors.Select(e => e.ErrorMessage)).ToList();

            return RedirectToAction("EnderecoEntrega", "Pedido");
        }
    }
}

src/web/NSE.WebApp.MVC/Controllers/PedidoController.cs
using Microsoft.AspNetCore.Mvc;
using NSE.WebApp.MVC.Models;
using NSE.WebApp.MVC.Service;
using System.Threading.Tasks;

namespace NSE.WebApp.MVC.Controllers
{
    public class PedidoController : MainController
    {
        private readonly IClienteService _clienteService;
        private readonly IComprasBffService _comprasBffService;

        public PedidoController(IClienteService clienteService,
            IComprasBffService comprasBffService)
        {
            _clienteService = clienteService;
            _comprasBffService = comprasBffService;
        }

        [HttpGet]
        [Route("endereco-de-entrega")]
        public async Task<IActionResult> EnderecoEntrega()
        {
            var carrinho = await _comprasBffService.ObterCarrinho();
            if (carrinho.Itens.Count == 0) return RedirectToAction("Index", "Carrinho");

            var endereco = await _clienteService.ObterEndereco();
            var pedido = _comprasBffService.MapearParaPedido(carrinho, endereco);

            return View(pedido);
        }

        [HttpGet]
        [Route("pagamento")]
        public async Task<IActionResult> Pagamento()
        {
            var carrinho = await _comprasBffService.ObterCarrinho();
            if (carrinho.Itens.Count == 0) return RedirectToAction("Index", "Carrinho");

            var pedido = _comprasBffService.MapearParaPedido(carrinho, null);

            return View(pedido);
        }

        [HttpPost]
        [Route("finalizar-pedido")]
        public async Task<IActionResult> FinalizarPedido(PedidoTransacaoViewModel pedidoTransacao)
        {
            if (!ModelState.IsValid) return View("Pagamento", _comprasBffService.MapearParaPedido(
                await _comprasBffService.ObterCarrinho(), null));

            var retorno = await _comprasBffService.FinalizarPedido(pedidoTransacao);

            if (ResponsePossuiErros(retorno))
            {
                var carrinho = await _comprasBffService.ObterCarrinho();
                if (carrinho.Itens.Count == 0) return RedirectToAction("Index", "Carrinho");

                var pedidoMap = _comprasBffService.MapearParaPedido(carrinho, null);
                return View("Pagamento", pedidoMap);
            }

            return RedirectToAction("PedidoConcluido");
        }

        [HttpGet]
        [Route("pedido-concluido")]
        public async Task<IActionResult> PedidoConcluido()
        {
            return View("ConfirmacaoPedido", await _comprasBffService.ObterUltimoPedido());
        }

        [HttpGet("meus-pedidos")]
        public async Task<IActionResult> MeusPedidos()
        {
            return View(await _comprasBffService.ObterListaPorClienteId());
        }
    }
}

src/web/NSE.WebApp.MVC/Views/Pedido/ConfirmacaoPedido.cshtml
@using NSE.WebApp.MVC.Extensions
@model NSE.WebApp.MVC.Models.PedidoViewModel

@{
    ViewData["Title"] = "Pedido confirmado!";
}

<section class="padding-y">
    <div class="container">

        <vc:Summary></vc:Summary>

        @{
            if (Model.PedidoItems.Any())
            {
                <div class="card">
                    <div class="tracking-wrap">
                        <div class="step active">
                            <span class="icon">
                                <i class="fa fa-location-arrow"></i>
                            </span>
                            <span class="text"> Endereço</span>
                        </div>
                        <div class="step active">
                            <span class="icon">
                                <i class="fa fa-credit-card"></i>
                            </span>
                            <span class="text"> Pagamento </span>
                        </div>
                        <div class="step active">
                            <span class="icon">
                                <i class="fa fa-check-square"></i>
                            </span>
                            <span class="text"> Confirmação</span>
                        </div>
                    </div>
                    <article class="card-body">
                        <header class="mb-4">
                            <h4 class="card-title">Pedido concluído com sucesso!</h4>
                        </header>
                        <div class="row">
                            @{
                                foreach (var item in Model.PedidoItems)
                                {
                                    <div class="col-md-6">
                                        <figure class="itemside  mb-3">
                                            <div class="aside">
                                                <img src="~/images/produtos/@item.Imagem" alt="@item.Nome" class="border img-xs">
                                            </div>
                                            <figcaption class="info">
                                                <p>
                                                    <b>@item.Nome</b>
                                                </p>
                                                <span>@this.UnidadesPorProdutoValorTotal(item.Quantidade, item.Valor) </span>
                                            </figcaption>
                                        </figure>
                                    </div>
                                }
                            }

                        </div>
                    </article>
                   
                    <header class="card-header">
                        <h3 class="d-inline-block mr-3">Pedido número: #@Model.Codigo</h3>
                    </header>
                    <article class="card-body border-top">

                        <div class="card-body">
                            <div class="row"> 
                                <div class="col-md-8">
                                    <h6 class="text-muted">Entregar em</h6>
                                    <p>
                                        @Model.Endereco.ToString()
                                    </p>
                                </div>
                                <div class="col-md-4">
                                    <h6 class="text-muted">Pagamento</h6>
                                    <span class="text-success">
                                        <i class="fas fa-credit-card"></i>
                                        Transação em cartão de crédito
                                    </span>
                                    <p>
                                        <span class="b">Total:  @this.FormatoMoeda(Model.ValorTotal)</span>
                                    </p>
                                </div>
                            </div>

                        </div>
                    </article>

                    <div class="card-body border-top">
                        <div class="text-left">
                            <a asp-controller="Pedido" asp-action="MeusPedidos" class="btn btn-primary float-md-right"> Meus Pedidos <i class="fa fa-chevron-right"></i> </a>
                        </div>
                    </div>

                </div>
            }
        }
    </div>
</section>

@section Scripts {

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

}

src/web/NSE.WebApp.MVC/Views/Pedido/EnderecoEntrega.cshtml
@using NSE.WebApp.MVC.Extensions
@model NSE.WebApp.MVC.Models.PedidoTransacaoViewModel

@{
    ViewData["Title"] = "Confirme o seu pedido";
}

<section class="padding-y">
    <div class="container">

        <vc:Summary></vc:Summary>

        @{
            if (Model.Itens.Any())
            {
                <div class="card">
                    <div class="tracking-wrap">
                        <div class="step active">
                            <span class="icon">
                                <i class="fa fa-location-arrow"></i>
                            </span>
                            <span class="text"> Endereço</span>
                        </div>
                        <div class="step">
                            <span class="icon">
                                <i class="fa fa-credit-card"></i>
                            </span>
                            <span class="text"> Pagamento </span>
                        </div>
                        <div class="step">
                            <span class="icon">
                                <i class="fa fa-check-square"></i>
                            </span>
                            <span class="text"> Confirmação</span>
                        </div>
                    </div>
                    <article class="card-body">
                        <header class="mb-4">
                            <h4 class="card-title">Seu pedido</h4>
                        </header>
                        <div class="row">
                            @{
                                foreach (var item in Model.Itens)
                                {
                                    <div class="d-flex col-md-3">
                                        <figure class="itemside  mb-3">
                                            <div class="aside">
                                                <img src="~/images/produtos/@item.Imagem" alt="@item.Nome" class="border img-xs" style="max-with: 100px; max-height: 100px">
                                            </div>
                                            <figcaption class="info">
                                                <p>
                                                    <b>@item.Nome</b>
                                                </p>
                                                <span>@this.UnidadesPorProdutoValorTotal(item.Quantidade, item.Valor) </span>
                                            </figcaption>
                                        </figure>
                                    </div>
                                }
                            }

                        </div>
                    </article>

                    <partial name="_ResumoFinanceiro" model="Model"/>

                    <div class="card-body border-top">
                        <partial name="_Endereco" model="Model"/>
                    </div>
                    <div class="card-body border-top">
                        @{
                            if (Model.Endereco != null)
                            {
                                <div class="text-left">
                                    <a asp-controller="Pedido" asp-action="Pagamento" class="btn btn-primary float-md-right"> Pagamento <i class="fa fa-chevron-right"></i> </a>
                                </div>
                            }
                        }

                        <a asp-controller="Carrinho" asp-action="Index" class="btn btn-light"> <i class="fa fa-chevron-left"></i> Voltar ao carrinho </a>
                    </div>
                </div>
            }
        }
    </div>
</section>

<partial name="_NovoEndereco" />

@section Scripts {

@{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
       $(document).ready(function() {
          BuscaCep();
       });
    </script>

}

src/web/NSE.WebApp.MVC/Views/Pedido/MeusPedidos.cshtml
@using NSE.WebApp.MVC.Extensions
@model IEnumerable<NSE.WebApp.MVC.Models.PedidoViewModel>

@{
    ViewData["Title"] = "Meus Pedidos";
}

<section class="padding-y">
    <div class="container">

        @{
            foreach (var pedido in Model.OrderBy(p => p.Data))
            {
                <div class="col-md-12" style="padding-bottom: 35px">
                    <article class="card">
                        <header class="card-header">
                            <b class="d-inline-block mr-3">Pedido ID: #@pedido.Codigo @Html.Raw(this.ExibeStatus(pedido.Status))</b>
                            <span>@pedido.Data.ToLongDateString()</span>
                        </header>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <h6 class="text-muted">Pagamento</h6>
                                    <span class="text-success">
                                        <i class="fas fa-credit-card"></i>
                                        Transação em cartão de crédito
                                    </span>

                                    <p>
                                        <span class="b">Total:  @this.FormatoMoeda(pedido.ValorTotal)</span>
                                    </p>

                                </div>
                                <div class="col-md-8">
                                    <h6 class="text-muted">Endereço de entrega</h6>
                                    <p>
                                        @pedido.Endereco.ToString()
                                    </p>
                                </div>
                            </div>
                            <hr>
                            <ul class="row">
                                @{
                                    foreach (var item in pedido.PedidoItems)
                                    {
                                        <li class="col-md-4">
                                            <figure class="itemside  mb-3">
                                                <div class="aside">
                                                    <img src="~/images/produtos/@item.Imagem" alt="@item.Nome" class="border img-xs" style="width: 120px; height: 120px" >
                                                </div>
                                                <figcaption class="info">
                                                    <p>
                                                        <b>@item.Nome</b>
                                                    </p>
                                                    <span>@this.UnidadesPorProdutoValorTotal(item.Quantidade, item.Valor) </span>
                                                </figcaption>
                                            </figure>
                                        </li>
                                    }
                                }
                            </ul>
                        </div>
                    </article>
                </div>
            }
        }
    </div>
</section>

src/web/NSE.WebApp.MVC/Views/Pedido/Pagamento.cshtml
@using NSE.WebApp.MVC.Extensions
@model NSE.WebApp.MVC.Models.PedidoTransacaoViewModel

@{
    ViewData["Title"] = "Confirme o seu pedido";
}

<section class="padding-y">
    <div class="container">

        <vc:Summary></vc:Summary>

        @{
            if (Model.Itens.Any())
            {
                <div class="card">
                    <div class="tracking-wrap">
                        <div class="step active">
                            <span class="icon">
                                <i class="fa fa-location-arrow"></i>
                            </span>
                            <span class="text"> Endereço</span>
                        </div>
                        <div class="step active">
                            <span class="icon">
                                <i class="fa fa-credit-card"></i>
                            </span>
                            <span class="text"> Pagamento </span>
                        </div>
                        <div class="step">
                            <span class="icon">
                                <i class="fa fa-check-square"></i>
                            </span>
                            <span class="text"> Confirmação</span>
                        </div>
                    </div>
                    <article class="card-body">
                        <header class="mb-4">
                            <h4 class="card-title">Seu pedido</h4>
                        </header>
                        <div class="row">
                            @{
                                foreach (var item in Model.Itens)
                                {
                                    <div class="col-md-3">
                                        <figure class="itemside  mb-3">
                                            <div class="aside">
                                                <img src="~/images/produtos/@item.Imagem" alt="@item.Nome" class="border img-xs" style="max-with: 100px; max-height: 100px">
                                            </div>
                                            <figcaption class="info">
                                                <p>
                                                    <b>@item.Nome</b>
                                                </p>
                                                <span>@this.UnidadesPorProdutoValorTotal(item.Quantidade, item.Valor) </span>
                                            </figcaption>
                                        </figure>
                                    </div>
                                }
                            }

                        </div>
                    </article>

                    <partial name="_ResumoFinanceiro" model="Model"/>

                    <form asp-action="FinalizarPedido" asp-controller="Pedido">
                        <article class="card-body border-top">

                            <div class="card-body">
                                   <div class="row">
                                    <div class="col-md-4 col-sm-12">
                                        <div class="form-group">
                                            <label asp-for="NomeCartao"></label>
                                            <input asp-for="NomeCartao" class="form-control"/>
                                            <span asp-validation-for="NomeCartao" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-12">
                                        <div class="form-group">
                                            <label asp-for="NumeroCartao"></label>
                                            <div class="input-group">
                                                <input asp-for="NumeroCartao" class="form-control"/>
                                                <div class="input-group-append">
                                                    <span class="input-group-text">
                                                        <i class="fab fa-cc-visa"></i> &nbsp; <i class="fab fa-cc-amex"></i> &nbsp;
                                                        <i class="fab fa-cc-mastercard"></i>
                                                    </span>
                                                </div>
                                                <span asp-validation-for="NumeroCartao" class="text-danger"></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-4 col-sm-12">
                                        <div>
                                            <label asp-for="ExpiracaoCartao"></label>
                                            <div class="form-inline">
                                                <input style="width: 190px" asp-for="ExpiracaoCartao" class="form-control"/>
                                                <span asp-validation-for="ExpiracaoCartao" class="text-danger"></span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-12">
                                        <div>
                                            <spam data-toggle="tooltip" title="" data-original-title="Os 3 dígitos informados atrás do seu cartão">
                                                <label asp-for="CvvCartao"></label> <i class="fa fa-question-circle"></i>
                                            </spam>

                                            <div>
                                                <input style="width: 160px" asp-for="CvvCartao" class="form-control"/>
                                                <span asp-validation-for="CvvCartao" class="text-danger"></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </article>

                        <div class="card-body border-top">
                            <div class="text-left">
                                <button type="submit" class="btn btn-primary float-md-right"> Finalizar Pedido <i class="fa fa-chevron-right"></i> </button>
                            </div>

                            <a asp-controller="Pedido" asp-action="EnderecoEntrega" class="btn btn-light"> <i class="fa fa-chevron-left"></i> Voltar ao Endereço </a>
                        </div>
                    </form>
                </div>
            }
        }
    </div>
</section>

@section Scripts {

@{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

src/web/NSE.WebApp.MVC/Views/Pedido/_Endereco.cshtml
@model NSE.WebApp.MVC.Models.PedidoTransacaoViewModel


<h4 class="card-title">Endereço</h4>
@{
    if (Model.Endereco == null)
    {
        <div class="text-left">
            <a href="javascript:void(0)" class="btn btn-primary float-md-left" data-toggle="modal" data-target="#enderecoModal"> <i class="fa fa-location-arrow"></i> Adicionar Endereço</a>
        </div>
    }
    else
    {
        <div class="row">
            <div class="col-9 text-left">
                @Model.Endereco.ToString()
            </div>
            <div class="col-3 text-right">
                <a href="javascript:void(0)" class="btn btn-primary float-md-right"> <i class="fa fa-location-arrow"></i> Alterar Endereço</a>
            </div>
        </div>
    }
}



src/web/NSE.WebApp.MVC/Views/Pedido/_NovoEndereco.cshtml
@model NSE.WebApp.MVC.Models.PedidoTransacaoViewModel
@{
    ViewData["Title"] = "Novo Endereço";
}

    <div class="modal fade" id="enderecoModal" tabindex="-1" role="dialog" aria-labelledby="enderecoModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div id="myModalContent">

                    <div class="modal-header">
                        <h4 class="modal-title">@ViewData["Title"]</h4>
                        <button type="button" class="close" data-dismiss="modal">
                            <span aria-hidden="true">×</span><span class="sr-only">Fechar</span>
                        </button>
                    </div>
                    
                    <form asp-action="NovoEndereco" asp-controller="Cliente">
                        <div class="modal-body">

                            <div class="form-group">
                                <label asp-for="Endereco.Cep"></label>
                                <input asp-for="Endereco.Cep" class="form-control" />
                                <span asp-validation-for="Endereco.Cep" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Endereco.Logradouro"></label>
                                <input asp-for="Endereco.Logradouro" class="form-control" />
                                <span asp-validation-for="Endereco.Logradouro" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Endereco.Numero"></label>
                                <input asp-for="Endereco.Numero" class="form-control" />
                                <span asp-validation-for="Endereco.Numero" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Endereco.Complemento"></label>
                                <input asp-for="Endereco.Complemento" class="form-control" />
                                <span asp-validation-for="Endereco.Complemento" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Endereco.Bairro"></label>
                                <input asp-for="Endereco.Bairro" class="form-control" />
                                <span asp-validation-for="Endereco.Bairro" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Endereco.Cidade"></label>
                                <input asp-for="Endereco.Cidade" class="form-control" />
                                <span asp-validation-for="Endereco.Cidade" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Endereco.Estado"></label>
                                <input asp-for="Endereco.Estado" class="form-control" />
                                <span asp-validation-for="Endereco.Estado" class="text-danger"></span>
                            </div>

                            <div class="modal-footer">
                                <div>
                                    <input type="submit" value="Cadastrar Endereço" class="btn btn-success" />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

<script>
    BuscaCep();
</script>

src/web/NSE.WebApp.MVC/Views/Pedido/_ResumoFinanceiro.cshtml
@using NSE.WebApp.MVC.Extensions
@model NSE.WebApp.MVC.Models.PedidoTransacaoViewModel

<article class="card-body border-top">
    <dl class="row">
        @{
            if (Model.VoucherUtilizado)
            {
            <dt class="col-sm-10">Subtotal: <span class="float-right text-muted">@Model.Itens.Sum(i => i.Quantidade) itens</span></dt>
            <dd class="col-sm-2 text-right">
                <strong>@this.FormatoMoeda(Model.ValorTotal + Model.Desconto)</strong>
            </dd>

            <dt class="col-sm-10">Desconto: <span class="float-right text-muted">@Model.VoucherCodigo</span></dt>
            <dd class="col-sm-2 text-danger text-right">
                <strong>@this.FormatoMoeda(Model.Desconto)</strong>
            </dd>
            }
        }
        <dt class="col-sm-10">Total:</dt>
        <dd class="col-sm-2 text-right">
            <strong class="h5 text-dark">@this.FormatoMoeda(Model.ValorTotal)</strong>
        </dd>
    </dl>
</article>