src/web/NSE.WebApp.MVC/Controllers/CarrrinhoController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NSE.WebApp.MVC.Models;
using NSE.WebApp.MVC.Service;

namespace NSE.WebApp.MVC.Controllers
{
    [Authorize]
    public class CarrinhoController : MainController
    {
        private readonly IComprasBffService _comprasBffService;
        public CarrinhoController(IComprasBffService comprasBffService)
        {
            _comprasBffService = comprasBffService;
        }

        [Route("carrinho")]
        public async Task<IActionResult> Index()
        {
            return View(await _comprasBffService.ObterCarrinho());
        }



        [HttpPost]
        [Route("carrinho/adicionar-item")]
        public async Task<IActionResult> AdicionarItemCarrinho(ItemCarrinhoViewModel itemCarrinho)
        {
            var resposta = await _comprasBffService.AdicionarItemCarrinho(itemCarrinho);

            if (ResponsePossuiErros(resposta)) return View("Index", await _comprasBffService.ObterCarrinho());

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Route("carrinho/atualizar-item")]
        public async Task<IActionResult> AtualizarItemCarrinho(Guid produtoId, int quantidade)
        {
            var item = new ItemCarrinhoViewModel { ProdutoId = produtoId, Quantidade = quantidade };
            var resposta = await _comprasBffService.AtualizarItemCarrinho(produtoId, item);

            if (ResponsePossuiErros(resposta)) return View("Index", await _comprasBffService.ObterCarrinho());

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Route("carrinho/remover-item")]
        public async Task<IActionResult> RemoverItemCarrinho(Guid produtoId)
        {
            var resposta = await _comprasBffService.RemoverItemCarrinho(produtoId);

            if (ResponsePossuiErros(resposta)) return View("Index", await _comprasBffService.ObterCarrinho());

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Route("carrinho/aplicar-voucher")]
        public async Task<IActionResult> AplicarVoucher(string voucherCodigo)
        {
            var resposta = await _comprasBffService.AplicarVoucherCarrinho(voucherCodigo);

            if (ResponsePossuiErros(resposta)) return View("Index", await _comprasBffService.ObterCarrinho());

            return RedirectToAction("Index");
        }
    }
}

src/web/NSE.WebApp.MVC/Controllers/CatalogoController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NSE.WebApp.MVC.Service;

namespace NSE.WebApp.MVC.Controllers
{
    public class CatalogoController : MainController
    {
        private readonly ICatalogoService _catalogoService;

        public CatalogoController(ICatalogoService catalogoService)
        {
            _catalogoService = catalogoService;
        }

        [HttpGet]
        [Route("")]
        [Route("vitrine")]
        public async Task<IActionResult> Index([FromQuery] int ps=8, [FromQuery] int page=1, [FromQuery] string q = null)
        {
            var produtos = await _catalogoService.ObterTodos(ps, page, q);
            ViewBag.Pesquisa = q;
            produtos.ReferenceAction = "Index";

            return View(produtos);
        }

        [HttpGet]
        [Route("produto-detalhe/{id}")]
        public async Task<IActionResult> ProdutoDetalhe(Guid id)
        {
            var produto = await _catalogoService.ObterPorId(id);

            return View(produto);
        }
    }
}

src/web/NSE.WebApp.MVC/Extensions/PaginacaoViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using NSE.WebApp.MVC.Models;

namespace NSE.WebApp.MVC.Extensions
{
    public class PaginacaoViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(IPagedList modeloPaginado)
        {
            return View(modeloPaginado);
        }
    }
}

src/web/NSE.WebApp.MVC/Views/Catalogo/Index.cshtml
@using NSE.WebApp.MVC.Extensions
@model PagedViewModel<NSE.WebApp.MVC.Models.ProdutoViewModel>

@{
    ViewData["Title"] = "Todos os produtos";
}

<section>
    <div>
        <div style="background-image: url(images/banners/Template.jpg); height: 100%; background-position: center; background-repeat: no-repeat; background-size: cover">
            <div style="text-align: center;">
                <img src="~/images/banners/nerdstore.png" />
            </div>
        </div>
        <div class="container" style=" padding-top: 20px">
            <div class="row" style="justify-content: center">
                @{
                    foreach (var produto in Model.List.Where(p => p.Ativo).OrderBy(p => p.Nome))
                    {
                        <div class="d-flex card m-2 p-2 justify-content-center" style="width: 23%" >  
                            <div href="#" >
                                <a asp-controller="Catalogo" asp-action="ProdutoDetalhe" asp-route-id="@produto.Id" style="width: 220px; height: 220px  " >
                                    <img src="~/images/produtos/@produto.Imagem" alt="@produto.Nome" class="img-fluid" style="object-fit: contain; min-width: 200px; max-width: 200px; min-height: 200px; max-height: 200px;" >
                                </a>
                                <figcaption class="info-wrap">
                                    <a asp-controller="Catalogo" asp-action="ProdutoDetalhe" asp-route-id="@produto.Id" class="title">
                                        <b> @produto.Nome</b> <br />
                                    </a>

                                    <small class="card=text">
                                        @this.MensagemEstoque(produto.QuantidadeEstoque)<br/><br/>
                                        @produto.Descricao
                                    </small>
                                </figcaption>
                                <div class="card-footer price mt-1">
                                    <h3>@this.FormatoMoeda(produto.Valor)</h3>
                                </div>
                            </div>
                        </div>
                    }
                }
            </div>

            <vc:paginacao modelo-paginado="@Model"></vc:paginacao>

        </div>
    </div>
</section>

src/web/NSE.WebApp.MVC/Views/Catalogo/ProdutoDetalhe.cshtml
@using NSE.WebApp.MVC.Extensions
@model NSE.WebApp.MVC.Models.ProdutoViewModel
@{
    ViewData["Title"] = Model.Nome;
}
<section class="section-content padding-y bg container">
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
                <article class="gallery-wrap">
                    <div class="img-big-wrap" style="text-align: center">
                        <img src="~/images/produtos/@Model.Imagem" alt="@Model.Nome" style="max-width: 80%;object-fit: contain">
                    </div>
                </article>
            </aside>
            <main class="col-md-6 border-left" style="padding-left: 20px">
                <article class="content-body">
                    <form asp-controller="Carrinho" asp-action="AdicionarItemCarrinho" method="post">

                        <input type="hidden" id="ProdutoId" name="ProdutoId" value="@Model.Id"/>

                        <h2 class="title">@Model.Nome</h2>

                        <div class="rating-wrap my-3">
                            <ul class="rating-stars">
                                <li style="width: 80%" class="stars-active">
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </li>
                                <li>
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </li>
                            </ul>
                            <small class="label-rating text-muted">132 avaliações</small>
                            <small class="label-rating text-success"> <i class="fa fa-clipboard-check"></i> 154 peças vendidas</small>
                        </div>

                        <div class="mb-3">
                            <var class="price h4">@this.FormatoMoeda(Model.Valor)</var>
                        </div>

                        <h5>@Model.Descricao</h5><br />
                        <p> @this.MensagemEstoque(Model.QuantidadeEstoque)</p>

                        <hr>

                        @{
                            if (Model.QuantidadeEstoque > 0)
                            {
                                <div class="form-row">
                                    <div class="form-group col-md flex-grow-0">
                                        <label>Quantidade</label>
                                        <div class="input-group input-spinner">
                                            <select id="Quantidade" name="Quantidade" class="form-control">

                                                <option value="1">1</option>
                                                <option value="2">2</option>
                                                <option value="3">3</option>
                                                <option value="4">4</option>
                                                <option value="5">5</option>
                                            </select>
                                        </div>
                                    </div>

                                </div>
                                <br />
                                <button type="submit" class="btn btn-outline-primary">
                                    <span class="text">Adicionar ao carrinho</span> <i class="fas fa-shopping-cart"> &nbsp;</i>
                                </button> 

                            }
                        }

                        <a asp-action="Index" class="btn  btn-info">
                            <span class="text">Voltar</span>
                        </a>
                    </form>
                </article>
            </main>
        </div>
    </div>
</section>