src/web/NSE.WebApp.MVC/Controllers/IdentidadeController.cs

using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using NSE.WebApp.MVC.Models;
using NSE.WebApp.MVC.Service;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Threading.Tasks;


namespace NSE.WebApp.MVC.Controllers
{
    public class IdentidadeController : MainController
    {
        private readonly IAutenticacaoService _autenticacaoService;

        public IdentidadeController(IAutenticacaoService autenticacaoService)
        {
            _autenticacaoService = autenticacaoService;
        }

        [HttpGet]
        [Route("nova-conta")]
        public IActionResult Registro()
        {
            return View();
        }

        [HttpPost]
        [Route("nova-conta")]
        public async Task<IActionResult> Registro(UsuarioRegistro usuarioRegistro)
        {
            if (!ModelState.IsValid) return View(usuarioRegistro);

            var resposta = await _autenticacaoService.Registro(usuarioRegistro);

            if (ResponsePossuiErros(resposta.ResponseResult)) return View(usuarioRegistro);

            await RealizarLogin(resposta);

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [Route("login")]
        public IActionResult Login(string returnUrl = null)
        {
            ViewData["ReturnUtl"] = returnUrl; 
            return View();
        }

        [HttpPost]
        [Route("login")]
        public async Task<IActionResult> Login(UsuarioLogin usuarioLogin, string returnUrl=null)
        {
            ViewData["ReturnUtl"] = returnUrl;
            if (!ModelState.IsValid) return View(usuarioLogin);

            var resposta = await _autenticacaoService.Login(usuarioLogin);

            if (ResponsePossuiErros(resposta.ResponseResult))
            {
                return View(usuarioLogin);
            }

            
            await RealizarLogin(resposta);

            if (string.IsNullOrEmpty(returnUrl))
            {
                return RedirectToAction("Index", "Catalogo");
            }


            return LocalRedirect(returnUrl);
        }

        [HttpGet]
        [Route("logout")]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }


        private async  Task RealizarLogin(UsuarioRespostaLogin resposta)
        {
            var token = ObterTokenFormatado(resposta.AccessToken);

            var claims = new List<Claim>();
            claims.Add(new Claim("JWT", resposta.AccessToken));
            claims.AddRange(token.Claims);

            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var authProperties = new AuthenticationProperties
            {
                ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(60),
                IsPersistent = true
            };

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity), authProperties);

        }

        private static JwtSecurityToken ObterTokenFormatado(string jwtToken)
        {
            return new JwtSecurityTokenHandler().ReadToken(jwtToken) as JwtSecurityToken;
        }
    }
}

src/web/NSE.WebApp.MVC/Views/Identidade/Login.cshtml
@model NSE.WebApp.MVC.Models.UsuarioLogin

@{
    ViewData["Title"] = "Log in";
}

<section class="section-conten padding-y container" style="min-height:35vh">
    
    <vc:Summary></vc:Summary>

    <div class="card mx-auto" style="max-width: 380px; margin-top: 100px;">
        
        <div class="card-body">
            <h4 class="card-title mb-4">Seja bem vindo!</h4>
            <form asp-route-returnurl="@ViewData["ReturnUrl"]" method="post">
                <div class="form-group">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Senha"></label>
                    <input type="password" asp-for="Senha" class="form-control" />
                    <span asp-validation-for="Senha" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">Entrar</button>
                </div>
            </form>
        </div>
        <div class="card-footer text-center">Ainda não tem uma conta?<a asp-controller="Identidade" asp-action="Registro"> Criar uma conta</a></div>
    </div>

</section>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

src/web/NSE.WebApp.MVC/Views/Identidade/Registro.cshtml
@model NSE.WebApp.MVC.Models.UsuarioRegistro

@{
	ViewData["Title"] = "Registro";
}
<section class="section-conten padding-y container" style="min-height:35vh">

	<vc:Summary></vc:Summary>
	<div class="card mx-auto" style="max-width: 680px; margin-top: 10px;">

		<div class="card-body">
			<h4 class="card-title mb-4">Welcome!</h4>
			<form asp-route-returnurl="@ViewData["ReturnUrl"]" method="post">



				<div class="form-group">
					<label asp-for="Nome"></label>
					<input asp-for="Nome" class="form-control" />
					<span asp-validation-for="Nome" class="text-danger"></span>
				</div>

				<div class="form-group">
					<label asp-for="Cpf"></label>
					<input asp-for="Cpf" class="form-control" />
					<span asp-validation-for="Cpf" class="text-danger"></span>
				</div>

				<div class="form-group">
					<label asp-for="Email"></label>
					<input asp-for="Email" class="form-control" />
					<span asp-validation-for="Email" class="text-danger"></span>
				</div>

				<div class="form-group">
					<label asp-for="Senha"></label>
					<input type="password" asp-for="Senha" class="form-control" />
					<span asp-validation-for="Senha" class="text-danger"></span>
				</div>

				<div class="form-group">
					<label asp-for="SenhaConfirmacao"></label>
					<input type="password" asp-for="SenhaConfirmacao" class="form-control" />
					<span asp-validation-for="SenhaConfirmacao" class="text-danger"></span>
				</div>

				<div class="form-group">
					<button type="submit" class="btn btn-primary">Enviar</button>
				</div>
			</form>
		</div>
		<div class="card-footer text-center">Already have an account?<a asp-controller="Identity" asp-action="Login"> Sign In</a></div>
	</div>
</section>



@section Scripts {
	<partial name="_ValidationScriptsPartial" />
}